### PR TITLE
Remove unused code `gen_code/gen_julia_code.jl`

### PR DESCRIPTION
**Pull request by mfasi**
After the `lincomb` update, there is a lot of unused code in this file. This PR is to clean things up a bit. I've only removed the obvious things for now, but it seems to me that everything having to do with the `axpby_header` can go, as this was only used in code that I've removed.

### CODE REVIEW

**Comment by jarlebring** [comment]
While we're doing cleanup.... Maybe drop legacy support?

https://github.com/matrixfunctions/GraphMatFun.jl/blob/873afcc1a66aa97b9963e6238a739d472f4871a2/src/code_gen/gen_julia_code.jl#L344

**Comment by mfasi** [comment]
All done, I think.

**Comment by jarlebring** [comment]
Nice!

**Comment by jarlebring** [comment]
Ready for merge? I would like to make a new release.

**Comment by mfasi** [comment]
> Ready for merge? I would like to make a new release.

I had forgotten about this one – I'll merge and I'm happy for a new release. Should this be 1.1.0?

**Comment by mfasi** [comment]
> 👍 Yes. This should be 1.1.0 according to julia version number guidelines.

All done – the version will be updated in the next merge round.

**Pull request merged**
